# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Post',
        ),
    ]
