# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0004_auto_20190527_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
