# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0005_auto_20190528_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='pictures/'),
        ),
    ]
