# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0007_auto_20190529_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='update bio', max_length=256),
        ),
    ]
