# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0011_auto_20190529_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='repo_link',
            new_name='project_url',
        ),
    ]
