# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0012_auto_20190529_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deployed_link',
        ),
    ]
