# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0013_remove_project_deployed_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pk']},
        ),
    ]
