# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0014_auto_20190529_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
    ]
