# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0016_project_landing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='landing_image',
            field=models.ImageField(blank=True, null=True, upload_to='site-images/'),
        ),
    ]
