# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0017_auto_20190529_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='awad.Profile'),
        ),
    ]
