# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0018_project_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
