# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0019_remove_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='landing_image',
        ),
    ]
