# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awad', '0021_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.ManyToManyField(max_length=30, related_name='imag', to='awad.Project'),
        ),
    ]
